### ISSUE TITLE
i-19-optimize-render-calculations

### ISSUE THREAD

**Issue by hans-sperling** [hans-sperling/Perspective-City#19]
### Description:
To speed up the rendering, a few optimizations should be implemented.

### Tasks:
- [x] Create render queue / order
- [x] Render by the queue (render order)
- [x] Caching functionality for distances
- [x] ~~Caching occuring heights and the resulting sizes of the shapes~~
- [x] ~~Caching complete occuring objects~~

**Comment by hans-sperling** [comment]
### Merges:
- https://github.com/hans-sperling/Perspective-City/pull/22
